"""Run the sequential stages in a pinnfluid YAML training manifest."""

from __future__ import annotations

import argparse
import json
import os
import subprocess
import sys
import time
from pathlib import Path

import yaml


ROOT = Path(__file__).resolve().parent.parent
_RUN_RESERVED = {'id', 'name', 'experiment_name', 'overrides'}
_BOOL_STORE_TRUE = {'no_wandb', 'eval_only'}
_BOOL_OPTIONAL = {'plot_eval', 'hard_ground_bc', 'amp', 'resume'}


def _load_manifest(path: Path) -> dict:
    with path.open('r', encoding='utf-8') as f:
        data = yaml.safe_load(f)
    if not isinstance(data, dict):
        raise ValueError(f'Invalid sweep manifest: {path}')
    runs = data.get('runs', [])
    if not isinstance(runs, list) or not runs:
        raise ValueError(f'No runs found in {path}')
    return data


def _python_literal(value) -> str:
    return repr(value)


def _write_config_override(path: Path, overrides: dict) -> None:
    lines = [
        '"""Auto-generated by pinnfluid/run_manifest.py. Do not edit manually."""',
        '',
    ]
    for key, value in overrides.items():
        if not isinstance(key, str) or not key or not key.replace('_', '').isalnum() or key.upper() != key:
            raise ValueError(f'Override keys must be ALL_CAPS config names, got: {key!r}')
        lines.append(f'{key} = {_python_literal(value)}')
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text('\n'.join(lines) + '\n', encoding='utf-8')


def _append_cli_arg(cmd: list[str], key: str, value) -> None:
    flag = f"--{key.replace('_', '-')}"
    if isinstance(value, bool):
        if key in _BOOL_STORE_TRUE:
            if value:
                cmd.append(flag)
            return
        if key in _BOOL_OPTIONAL:
            cmd.append(flag if value else f"--no-{key.replace('_', '-')}")
            return
        raise ValueError(f'Unsupported boolean CLI field: {key}')
    if value is None or value == '':
        return
    cmd.extend([flag, str(value)])


def _run_command(cmd: list[str], *, env: dict[str, str] | None = None) -> None:
    print('\n[RUN]', ' '.join(cmd), flush=True)
    subprocess.run(cmd, check=True, cwd=str(ROOT), env=env)


def _default_state_path(manifest_path: Path) -> Path:
    return ROOT / 'results' / '_sweeps' / f'{manifest_path.stem}_state.json'


def _load_state(path: Path, *, manifest_path: Path) -> dict:
    if path.exists():
        with path.open('r', encoding='utf-8') as f:
            data = json.load(f)
        if isinstance(data, dict) and data.get('sweep_yaml') == str(manifest_path.resolve()):
            data.setdefault('runs', {})
            return data
    return {
        'sweep_yaml': str(manifest_path.resolve()),
        'updated_at': None,
        'runs': {},
    }


def _save_state(path: Path, payload: dict) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    payload['updated_at'] = int(time.time())
    with path.open('w', encoding='utf-8') as f:
        json.dump(payload, f, indent=2, sort_keys=False)


def main() -> None:
    ap = argparse.ArgumentParser(description='Run a pinnfluid training manifest.')
    ap.add_argument('--sweep-yaml', required=True, help='Path to YAML manifest')
    ap.add_argument('--only-run', default='', help='Optional run id filter')
    ap.add_argument('--override-path', default='', help='Optional path for the generated override file. If omitted, a unique file is created under /tmp.')
    ap.add_argument('--state-path', default='', help='Optional JSON file used to persist sweep progress across pod restarts.')
    args = ap.parse_args()

    manifest_path = Path(args.sweep_yaml)
    if not manifest_path.is_absolute():
        manifest_path = ROOT / manifest_path
    manifest = _load_manifest(manifest_path)
    state_path = Path(args.state_path) if args.state_path else _default_state_path(manifest_path)
    if not state_path.is_absolute():
        state_path = (ROOT / state_path).resolve()
    state = _load_state(state_path, manifest_path=manifest_path)
    print(f'[INFO] Sweep state file: {state_path}', flush=True)

    base = manifest.get('base', {})
    if base is None:
        base = {}
    if not isinstance(base, dict):
        raise ValueError("'base' must be a mapping.")

    for idx, run in enumerate(manifest['runs'], start=1):
        if not isinstance(run, dict):
            raise ValueError(f'Run #{idx} is not a mapping.')
        run_id = str(run.get('id', run.get('name', f'run_{idx:02d}')))
        if args.only_run and run_id != str(args.only_run):
            continue

        experiment_name = str(run.get('experiment_name', '')).strip()
        if not experiment_name:
            raise ValueError(f'Run {run_id} missing experiment_name.')
        run_state = dict(state.get('runs', {}).get(run_id, {}))
        if run_state.get('status') == 'completed':
            print(f'\n=== Sweep run {idx}: {run_id} already completed, skipping ===', flush=True)
            continue

        overrides = dict(base.get('overrides', {}))
        overrides.update(run.get('overrides', {}))
        if args.override_path:
            override_path = Path(args.override_path)
            if not override_path.is_absolute():
                override_path = (ROOT / override_path).resolve()
        else:
            override_path = Path(f'/tmp/pinnfluid_override_{run_id}_{os.getpid()}.py')

        cli_args = {k: v for k, v in base.items() if k not in _RUN_RESERVED and k != 'overrides'}
        cli_args.update({k: v for k, v in run.items() if k not in _RUN_RESERVED})

        cmd = [sys.executable, '-u', 'pinnfluid/main.py', '--experiment-name', experiment_name]
        for key, value in cli_args.items():
            _append_cli_arg(cmd, key, value)

        env = os.environ.copy()
        if overrides:
            _write_config_override(override_path, overrides)
            env['PINN_CONFIG_OVERRIDE_PATH'] = str(override_path)
        else:
            env.pop('PINN_CONFIG_OVERRIDE_PATH', None)

        print(f'\n=== Sweep run {idx}: {run_id} -> {experiment_name} ===', flush=True)
        if overrides:
            print(f'[INFO] Overrides: {overrides}', flush=True)
            print(f'[INFO] Override file: {override_path}', flush=True)
        run_state.update({
            'status': 'running',
            'experiment_name': experiment_name,
            'attempts': int(run_state.get('attempts', 0)) + 1,
            'last_started_at': int(time.time()),
        })
        state['runs'][run_id] = run_state
        _save_state(state_path, state)
        try:
            _run_command(cmd, env=env)
            run_state['status'] = 'completed'
            run_state['last_completed_at'] = int(time.time())
            state['runs'][run_id] = run_state
            _save_state(state_path, state)
        finally:
            if overrides and override_path.exists():
                override_path.unlink()


if __name__ == '__main__':
    main()
